[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
env_logger = "0.11.6"
mongodb = "3.2.0"
futures-util = "0.3"